const { existsSync, readFileSync, writeFileSync, unlinkSync } = require("fs");
const { join } = require("path");

const ALL_GATES = [
  ["E1-precision", "Exact-match precision"],
  ["E1-substitution", "Silent variant substitution"],
  ["E2-parser", "Query field accuracy"],
  ["E3-latency", "Match latency"],
  ["E8-privacy", "Wishlist leakage"],
  ["E13-ranking", "Multi-match ranking"],
];

module.exports = () => {
  const root = join(__dirname, "..", "..");
  const resultsFile = join(root, "docs", ".gate-results.jsonl");
  if (!existsSync(resultsFile)) return;

  const results = readFileSync(resultsFile, "utf8")
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line));

  // A partial run must say so. A report that silently omits the gates that did
  // not run reads as if they passed.
  if (results.length === 0) {
    unlinkSync(resultsFile);
    return;
  }

  const ran = new Set(results.map((r) => r.id));
  const missing = ALL_GATES.filter(([id]) => !ran.has(id));

  const rows = results.map(
    (r) =>
      `| ${r.epic} | ${r.requirement} | **${r.measured}** | ${r.pass ? "pass" : "**FAIL**"} |`
  );

  const lines = [
    "# Acceptance gate report",
    "",
    "Generated by `npm run gates`. Every row is measured on the committed",
    "catalog, so two runs on two machines produce the same numbers.",
    "",
    `Run at ${new Date().toISOString()}.`,
    "",
    "| Epic | Requirement | Measured | Result |",
    "|---|---|---|---|",
    ...rows,
    "",
    "## What each number is not evidence for",
    "",
    ...results.map((r) => `- **${r.epic}** — ${r.caveat}`),
    "",
  ];

  if (missing.length > 0) {
    lines.push(
      "## Not run in this invocation",
      "",
      ...missing.map(([id, name]) => `- ${id} (${name})`),
      "",
      "Run `npm run gates` for the complete set.",
      ""
    );
  }

  writeFileSync(join(root, "docs", "gate-report.md"), lines.join("\n"));
  unlinkSync(resultsFile);
};
