import { writeFileSync } from "fs";
import { join } from "path";
import { seeded } from "@/analytics/random";
import {
  detectableEffect,
  panelSizeFor,
  perArmFixedHorizon,
  perArmSequential,
  studyDurationDays,
  type PanelInputs,
} from "@/analytics/power";
import { alwaysValidInterval } from "@/experiment/sequential";

const REPORT = join(__dirname, "..", "..", "docs", "panel-sizing.md");

/** Measured in the shadow run: how often a search produced a candidate. */
const MEASURED_OPPORTUNITY = 0.476;

const BASE: PanelInputs = {
  effectOnExposed: 0.05,
  baseRate: 0.18,
  engagementRate: 0.8,
  saveRate: 0.85,
  // A panellist searching three times sees the module at least once with
  // probability 1 - (1 - 0.476)^3.
  exposureRate: 1 - (1 - MEASURED_OPPORTUNITY) ** 3,
  arms: 3,
  sequential: true,
  comparison: "treatment_vs_control",
};

/**
 * Empirical power, against the estimator the experiment will actually use.
 *
 * The formula is textbook; the interval is not. `alwaysValidInterval` is a
 * confidence sequence, deliberately wider than a fixed-horizon interval, so a
 * sample size derived from a normal approximation might or might not deliver
 * the power it claims. Measuring it is the difference between a number and an
 * assertion.
 */
function empiricalPower(
  perArm: number,
  baseRate: number,
  effect: number,
  replications = 2000,
  seed = 31415
): number {
  const random = seeded(seed);
  let detected = 0;

  for (let r = 0; r < replications; r += 1) {
    let controlSuccesses = 0;
    let treatmentSuccesses = 0;
    for (let i = 0; i < perArm; i += 1) {
      if (random() < baseRate) controlSuccesses += 1;
      if (random() < baseRate + effect) treatmentSuccesses += 1;
    }
    const interval = alwaysValidInterval(
      { successes: controlSuccesses, trials: perArm },
      { successes: treatmentSuccesses, trials: perArm }
    );
    if (interval.significant) detected += 1;
  }
  return detected / replications;
}

describe("panel sizing", () => {
  it("writes docs/panel-sizing.md", () => {
    const planGuess = 400;

    // What the plan's own guess can actually see.
    const guessDetects = detectableEffect(planGuess, {
      baseRate: BASE.baseRate,
      engagementRate: BASE.engagementRate,
      saveRate: BASE.saveRate,
      exposureRate: BASE.exposureRate,
      arms: BASE.arms,
      sequential: true,
      comparison: "treatment_vs_control",
    });
    const guessDetectsBMinusA = detectableEffect(planGuess, {
      baseRate: BASE.baseRate,
      engagementRate: BASE.engagementRate,
      saveRate: BASE.saveRate,
      exposureRate: BASE.exposureRate,
      arms: BASE.arms,
      sequential: true,
      comparison: "b_minus_a",
    });

    const scenarios = [
      { label: "B vs control, 5pp lift", inputs: BASE },
      { label: "B vs control, 3pp lift", inputs: { ...BASE, effectOnExposed: 0.03 } },
      { label: "B vs control, 2pp lift", inputs: { ...BASE, effectOnExposed: 0.02 } },
      {
        label: "B − A, 5pp vs 3pp",
        inputs: { ...BASE, comparison: "b_minus_a" as const, sharedFraction: 0.6 },
      },
    ].map((scenario) => ({ ...scenario, result: panelSizeFor(scenario.inputs) }));

    // Sensitivity to the one input nobody has data for.
    const baseRates = [0.1, 0.15, 0.18, 0.25, 0.35];
    const sensitivity = baseRates.map((baseRate) => ({
      baseRate,
      panel: panelSizeFor({ ...BASE, baseRate }).panelSize,
    }));

    const headline = scenarios[0].result;
    const fixed = perArmFixedHorizon({
      baseRate: BASE.baseRate,
      mde: headline.observableEffect,
    });
    const sequential = perArmSequential({
      baseRate: BASE.baseRate,
      mde: headline.observableEffect,
    });

    const power = empiricalPower(headline.perArm, BASE.baseRate, headline.observableEffect);
    const powerAtHalf = empiricalPower(
      Math.floor(headline.perArm / 2),
      BASE.baseRate,
      headline.observableEffect,
      2000,
      27182
    );

    const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
    const pp = (value: number) =>
      Number.isFinite(value) ? `${(value * 100).toFixed(2)}pp` : "no detectable effect";

    const lines = [
      "# Panel sizing for the Phase 4 experiment",
      "",
      "Generated by `npm run panel`. Regenerate rather than edit.",
      "",
      "The plan guesses **300–500 recruited testers** (§7.4 and the risk register)",
      "and nothing had ever checked that guess. This checks it.",
      "",
      "## Headline",
      "",
      `A panel of **${planGuess}** supports **${pp(guessDetects)}** for B against control —`,
      Number.isFinite(guessDetects)
        ? "a lift that large on a base of 18% would be extraordinary, so in practice this panel cannot answer the question."
        : "no effect small enough to be real, and none large enough to be possible. It cannot answer the question at all.",
      "",
      `For the B − A comparison §7 actually asks for, the same panel supports **${pp(guessDetectsBMinusA)}**.`,
      "",
      `Detecting a 5pp lift on the exposed needs a panel of **${headline.panelSize.toLocaleString("en-IN")}**.`,
      `Answering "is variant continuity the mechanism" needs **${scenarios[3].result.panelSize.toLocaleString("en-IN")}**.`,
      "",
      "The plan's guess is not slightly short. It is short by more than an order",
      "of magnitude for the question the experiment exists to answer.",
      "",
      "## Why the number is so much larger than it looks",
      "",
      "Three multipliers sit between a recruited person and a usable observation,",
      "and none of them is the sample-size formula.",
      "",
      "**Three arms.** Control, A and B. The panel splits three ways before",
      "anything else happens.",
      "",
      "**Intent-to-treat dilution.** A user assigned to a treatment who never sees",
      `the module behaves exactly like control. At the measured opportunity rate of ${pct(MEASURED_OPPORTUNITY)},`,
      `a panellist searching three times is exposed at least once with probability ${pct(BASE.exposureRate)}.`,
      "The observed effect is the true effect scaled by that, and sample size",
      "scales with its square.",
      "",
      "**B − A is a smaller effect than either.** §7 splits the treatments to learn",
      "*where* a lift comes from. If A delivers 3 points and B delivers 5, the",
      "question \"is variant continuity doing the work\" is a 2-point question,",
      "measured between two treatment arms rather than against the full control",
      "group. Powering for \"B beats control\" and stopping there leaves the actual",
      "question unanswerable — and that failure is invisible until the read-out.",
      "",
      "## Scenarios",
      "",
      "| Question | Effect on exposed | Effect the estimator sees | Per arm | Cohort entrants | **Panel** |",
      "|---|---|---|---|---|---|",
      ...scenarios.map(
        (s) =>
          `| ${s.label} | ${pp(s.inputs.effectOnExposed)} | ${pp(s.result.observableEffect)} | ${s.result.perArm.toLocaleString("en-IN")} | ${s.result.cohortEntrants.toLocaleString("en-IN")} | **${s.result.panelSize.toLocaleString("en-IN")}** |`
      ),
      "",
      "## The cost of being allowed to peek",
      "",
      `Fixed-horizon would need **${fixed.toLocaleString("en-IN")}** per arm; the confidence sequence needs **${sequential.toLocaleString("en-IN")}** — about ${(sequential / fixed).toFixed(2)}× more.`,
      "",
      "That is the price of a staged ramp. It buys the right to stop whenever the",
      "guardrails or the numbers say so, which a fixed-horizon design does not",
      "have. Paying it is a choice; not paying it and peeking anyway is not a",
      "cheaper design, it is an invalid one.",
      "",
      "## Validation — does the size deliver the power it claims?",
      "",
      "The formula is a normal approximation. The estimator is a confidence",
      "sequence, deliberately wider. Whether the first delivers what it promises",
      "through the second is a question for measurement, not for algebra.",
      "",
      `At **${headline.perArm.toLocaleString("en-IN")}** per arm, 2,000 simulated experiments detected the effect **${pct(power)}** of the time (target 80%).`,
      `At half that size, **${pct(powerAtHalf)}** — the size is doing the work, not the arithmetic.`,
      "",
      "## Sensitivity to the base rate",
      "",
      "The base 30-day wishlist-to-purchase rate is **assumed, not measured**. It",
      "is the input the answer is most sensitive to, and no data for it exists.",
      "",
      "| Assumed base rate | Panel needed |",
      "|---|---|",
      ...sensitivity.map(
        (row) => `| ${pct(row.baseRate)} | ${row.panel.toLocaleString("en-IN")} |`
      ),
      "",
      "Getting this number from production analytics before recruiting anyone is",
      "the single cheapest thing available. Every figure above moves with it.",
      "",
      "## Duration",
      "",
      `Censoring is a scheduling fact, not a sample-size problem: the study has to outlast the last save by the 30-day window. Recruiting over 14 days means running for **${studyDurationDays(14)} days** minimum.`,
      "",
      "Counting an unclosed window as a non-conversion would depress the rate and",
      "then let it drift upward for a month, which is indistinguishable from a",
      "real effect.",
      "",
      "## What this means for the decision",
      "",
      "A panel of 300–500 is not useless — it is useless *for this metric*. It is",
      "the right size for the questions that do not need a cohort:",
      "",
      "- Do participants understand why the module appeared? (§4 target: ≥80%)",
      "- Can they recover from an unavailable variant?",
      "- Do the ten states read correctly?",
      "- Is the Buy/Compare split driven by the button fills? (§4.4's swapped-fill check)",
      "",
      "Those are usability questions with usability sample sizes, and the",
      "prototype can answer them now. The 30-day rate needs either a panel an",
      "order of magnitude larger, or production traffic.",
      "",
      "## What this report is not evidence for",
      "",
      "- The base conversion rate, engagement and save rates are assumed. Only the opportunity rate is measured, and it was measured over catalog-generated queries rather than real traffic — real queries are heavier in the head and would move it.",
      "- Power is validated against the estimator on binomial draws, which assumes users are independent and identically distributed. Real panellists are neither.",
      "- The B − A figure assumes A delivers 60% of B's lift. That fraction is a guess, and the whole point of the experiment is that nobody knows it.",
      "",
    ];

    writeFileSync(REPORT, lines.join("\n"));

    expect(headline.panelSize).toBeGreaterThan(planGuess);
    expect(power).toBeGreaterThan(0.7);
    expect(power).toBeLessThan(0.95);
    expect(powerAtHalf).toBeLessThan(power);
  });
});
