import { writeFileSync } from "fs";
import { join } from "path";
import catalogJson from "@/data/catalog.json";
import wishlistJson from "@/data/wishlist.json";
import type { Catalog, Wishlist } from "@/data/types";
import { DEFAULT_CONFIG, type Modality } from "@/match/contract";
import {
  buyFromWishlistRate,
  compareOptionsRate,
  dismissalRate,
  duplicateAddRate,
  latencyAndErrorRate,
  matchExposureRate,
  matchPrecision,
  savedItemPurchaseRate,
  searchToPurchaseRate,
  shadowOpportunityRate,
  thirtyDayWishlistToPurchaseRate,
  variantRecoveryRate,
  type Rate,
} from "@/analytics/metrics";
import { recommendTau, runShadow } from "@/analytics/shadow";
import { simulate } from "@/analytics/simulate";

const catalog = catalogJson as unknown as Catalog;
const wishlist = wishlistJson as unknown as Wishlist;
const REPORT = join(__dirname, "..", "..", "docs", "shadow-report.md");

const pct = (rate: Rate) =>
  rate.value === null ? "n/a" : `${(rate.value * 100).toFixed(1)}%`;
const frac = (rate: Rate) => `${rate.numerator} / ${rate.denominator}`;

/**
 * The Phase 3 read-out (plan S8-S9), written to docs/shadow-report.md.
 *
 * Two independent halves, and conflating them would be the easiest way to
 * mislead someone with this file:
 *
 *   the shadow run is real -- the actual matcher over the actual catalog,
 *     producing genuine opportunity volume and a genuine threshold sweep;
 *   the metric read-out is simulated -- there are no users, so the population
 *     is synthetic and its lift was planted by hand.
 *
 * The first tells you something about the feature. The second tells you only
 * that the models compute. The report says so in both places.
 */
describe("shadow-mode report", () => {
  it("writes docs/shadow-report.md", () => {
    const shadow = runShadow(catalog, wishlist);
    const { log, asOf, injected } = simulate({ users: 3000, seed: 2026 });
    const events = log.all();

    const modalities: Modality[] = ["text", "voice", "image"];
    const recommended = modalities.map((modality) => recommendTau(shadow.sweep, modality));

    const cohort = {
      control: thirtyDayWishlistToPurchaseRate(events, asOf, "control"),
      a: thirtyDayWishlistToPurchaseRate(events, asOf, "treatment_a"),
      b: thirtyDayWishlistToPurchaseRate(events, asOf, "treatment_b"),
    };
    const latency = latencyAndErrorRate(events);

    const sweepRows = shadow.sweep
      .filter((row) => row.rendered > 0)
      .map(
        (row) =>
          `| ${row.tau.toFixed(2)} | ${(row.opportunityRate * 100).toFixed(1)}% | ${row.precision === null ? "n/a" : `${(row.precision * 100).toFixed(1)}%`} | ${row.meanConfidence.toFixed(3)} |`
      );

    const lines = [
      "# Shadow-mode read-out (Phase 3)",
      "",
      "Generated by `npm run shadow`. Regenerate rather than edit.",
      "",
      "> **Two halves, different standing.** The shadow run below is real: the",
      "> actual matcher over the committed catalog. The metric read-out is",
      "> computed over a *simulated* population, because a greenfield prototype",
      "> has no users — the plan says as much in its risk register. Simulated",
      "> numbers demonstrate that the models compute; they are not findings",
      "> about the feature, and no decision should rest on them.",
      "",
      "## 1. Shadow run — real",
      "",
      `Matching ran ${shadow.evaluated.toLocaleString("en-IN")} times across three modalities and rendered nothing.`,
      "",
      "| | |",
      "|---|---|",
      `| Evaluations | ${shadow.evaluated.toLocaleString("en-IN")} |`,
      `| Would have rendered | ${shadow.withCandidates.toLocaleString("en-IN")} (**${(shadow.opportunityRate * 100).toFixed(1)}%** opportunity rate) |`,
      `| Tier 1 / tier 2 candidates | ${shadow.tierMix.tier1.toLocaleString("en-IN")} / ${shadow.tierMix.tier2.toLocaleString("en-IN")} |`,
      `| Saved items ineligible on identity | ${shadow.ineligibleOnIdentity} of ${wishlist.items.length} |`,
      "",
      "### Search latency delta — the S8 gate",
      "",
      `Search alone: **${shadow.latency.searchAlone.toFixed(4)} ms** per query.`,
      `Search with matching in the same tick: **${shadow.latency.searchWithMatch.toFixed(4)} ms**.`,
      `Delta: **${shadow.latency.deltaMs >= 0 ? "+" : ""}${shadow.latency.deltaMs.toFixed(4)} ms**.`,
      "",
      "The delta is noise, and structurally has to be: `search()` takes no",
      "wishlist argument and returns synchronously, so there is no ordering in",
      "which it could wait on the match call. This measures that the property",
      "holds; it does not measure a deployed service under load.",
      "",
      "## 2. Threshold sweep — real",
      "",
      "What each candidate τ costs in volume and buys in confidence. This is the",
      "S9 tuning deliverable.",
      "",
      "| τ | Opportunity | Precision | Mean confidence |",
      "|---|---|---|---|",
      ...sweepRows,
      "",
      "One table, not three: a candidate's confidence does not depend on the",
      "input modality. Modality selects which row you apply, which is why the",
      "C-8 requirement for a higher voice and image bar is a threshold decision",
      "rather than a scoring one.",
      "",
      "### Recommended τ",
      "",
      "| Modality | Current | Recommended | Supported by this sweep |",
      "|---|---|---|---|",
      ...recommended.map(
        (row) =>
          `| ${row.modality} | ${row.current.toFixed(2)} | ${row.recommended.toFixed(2)} | ${row.supported ? "yes" : "**no — keep current**"} |`
      ),
      "",
      ...(recommended.every((row) => !row.supported)
        ? [`> ${recommended[0].rationale}`, ""]
        : []),
      "",
      "Where the sweep can discriminate, the base is the lowest τ meeting the 99%",
      "precision target the E1 gate sets: constraint C-4 puts a false positive",
      "above a miss, but there is no reason to pay volume for precision already",
      "bought. Voice and image then step up one rung: constraint C-8 demands a",
      "higher bar for them, and since the score is",
      "modality-blind the threshold is the only lever available. That margin is",
      "buying back transcription and recognition error the score cannot see.",
      "",
      "## 3. Metric read-out — simulated",
      "",
      `${(3000).toLocaleString("en-IN")} synthetic users over 45 days, evenly assigned across three arms.`,
      "",
      "| Metric | Role | Control | Treatment A | Treatment B |",
      "|---|---|---|---|---|",
      `| Match exposure rate | Opportunity | ${pct(matchExposureRate(events, "control"))} | ${pct(matchExposureRate(events, "treatment_a"))} | ${pct(matchExposureRate(events, "treatment_b"))} |`,
      `| Match precision | Quality gate | ${pct(matchPrecision(events, "control"))} | ${pct(matchPrecision(events, "treatment_a"))} | ${pct(matchPrecision(events, "treatment_b"))} |`,
      `| Buy-from-Wishlist rate | Mechanism | ${pct(buyFromWishlistRate(events, "control"))} | ${pct(buyFromWishlistRate(events, "treatment_a"))} | ${pct(buyFromWishlistRate(events, "treatment_b"))} |`,
      `| Compare-options rate | Mechanism | ${pct(compareOptionsRate(events, "control"))} | ${pct(compareOptionsRate(events, "treatment_a"))} | ${pct(compareOptionsRate(events, "treatment_b"))} |`,
      `| Saved-item purchase rate | Direct impact | ${pct(savedItemPurchaseRate(events, "control"))} | ${pct(savedItemPurchaseRate(events, "treatment_a"))} | ${pct(savedItemPurchaseRate(events, "treatment_b"))} |`,
      `| Search-to-purchase rate | **Guardrail** | ${pct(searchToPurchaseRate(events, "control"))} | ${pct(searchToPurchaseRate(events, "treatment_a"))} | ${pct(searchToPurchaseRate(events, "treatment_b"))} |`,
      `| Dismissal rate | Relevance | ${pct(dismissalRate(events, "control"))} | ${pct(dismissalRate(events, "treatment_a"))} | ${pct(dismissalRate(events, "treatment_b"))} |`,
      `| Duplicate-add rate | Flow integrity | ${pct(duplicateAddRate(events, "control"))} | ${pct(duplicateAddRate(events, "treatment_a"))} | ${pct(duplicateAddRate(events, "treatment_b"))} |`,
      `| Variant recovery rate | Fashion quality | ${pct(variantRecoveryRate(events, "control"))} | ${pct(variantRecoveryRate(events, "treatment_a"))} | ${pct(variantRecoveryRate(events, "treatment_b"))} |`,
      "",
      `Latency p50 / p95 / p99: **${latency.p50.toFixed(1)} / ${latency.p95.toFixed(1)} / ${latency.p99.toFixed(1)} ms**. Error rate **${pct(latency.errorRate)}** (timeouts ${frac(latency.timeoutRate)}).`,
      "",
      "## 4. Cohort model validation",
      "",
      "The primary metric is a 30-day user-level rate. The check that matters is",
      "not whether the model produces a number — anything does — but whether it",
      "recovers an effect that was planted.",
      "",
      "| Arm | Entered | Converted | Rate | Injected lift | Recovered lift |",
      "|---|---|---|---|---|---|",
      `| Control | ${cohort.control.entered} | ${cohort.control.converted} | ${pct(cohort.control.rate)} | — | — |`,
      `| Treatment A | ${cohort.a.entered} | ${cohort.a.converted} | ${pct(cohort.a.rate)} | +${(injected.treatment_a * 100).toFixed(1)}pp | **+${((cohort.a.rate.value! - cohort.control.rate.value!) * 100).toFixed(1)}pp** |`,
      `| Treatment B | ${cohort.b.entered} | ${cohort.b.converted} | ${pct(cohort.b.rate)} | +${(injected.treatment_b * 100).toFixed(1)}pp | **+${((cohort.b.rate.value! - cohort.control.rate.value!) * 100).toFixed(1)}pp** |`,
      "",
      `${cohort.control.censored + cohort.a.censored + cohort.b.censored} users were censored — their 30-day window had not closed by ${asOf}. Counting them as non-conversions would depress the rate and then let it drift upward for a month, which is indistinguishable from a real effect.`,
      "",
      "## What this report is not evidence for",
      "",
      "- The opportunity rate is measured over queries the catalog can generate, not over real search traffic. Real traffic is heavier in the head and would move this number.",
      "- Every arm difference in section 3 and 4 was planted by the simulator. They demonstrate that the models detect an effect; they say nothing about whether the feature has one.",
      "- The latency delta is in-process JavaScript. It shows search does not wait on matching. It does not show a deployed service meets its SLO.",
      "- Operational precision treats a dismissal as a negative label and an action as a positive one. Exposures that drew neither are unlabelled and excluded, so the denominator is small and the figure is directional.",
      "",
    ];

    writeFileSync(REPORT, lines.join("\n"));

    // The report is the deliverable, but a few invariants have to hold or it
    // is misleading rather than merely incomplete.
    expect(shadow.evaluated).toBeGreaterThan(0);
    expect(Math.abs(shadow.latency.deltaMs)).toBeLessThan(1);
    expect(cohort.b.rate.value! - cohort.control.rate.value!).toBeGreaterThan(0);
  });
});
