import type {
  Colourway,
  ParentProduct,
  Wishlist,
  WishlistItem,
} from "@/data/types";

/**
 * The wishlist at runtime.
 *
 * `data/wishlist.json` is generated by build.py and must not be hand-edited,
 * and every gate and scenario is pinned to the eleven fixture items and their
 * roles. So this seeds from that file and layers the user's own saves on top,
 * in memory, for the session -- the same shape TagStore already uses for the
 * same reason.
 *
 * Nothing here writes back to the fixture. A gate importing wishlist.json sees
 * exactly what it saw before, which is the point: the measured set must not
 * depend on what somebody clicked while demoing.
 *
 * Until this existed the heart on every product tile was a decoration -- a
 * `View`, not a `Pressable` -- and there was no way to save anything from
 * anywhere in the app. The prototype could only ever reconnect you with the
 * eleven items it shipped with.
 */

/** Distinguishes a save the user made from the generated state fixtures. */
export const USER_SAVED_ROLE = "user_saved";

export class WishlistStore {
  private state: WishlistItem[];
  readonly userId: string;
  readonly pincode: string;
  /** Bumped on every change, so React has something to depend on. */
  version = 0;

  constructor(seed: Wishlist) {
    this.state = [...seed.items];
    this.userId = seed.user_id;
    this.pincode = seed.pincode;
  }

  get items(): WishlistItem[] {
    return this.state;
  }

  /** The shape MatchClient and revalidate() expect. */
  asWishlist(): Wishlist {
    return { user_id: this.userId, pincode: this.pincode, items: this.state };
  }

  savedProductIds(): Set<number> {
    return new Set(this.state.map((item) => item.product_id));
  }

  isSaved(productId: number): boolean {
    return this.state.some((item) => item.product_id === productId);
  }

  findByProduct(productId: number): WishlistItem | undefined {
    return this.state.find((item) => item.product_id === productId);
  }

  add(
    parent: ParentProduct,
    colourway: Colourway,
    size: string,
    savedAt: string
  ): WishlistItem {
    const existing = this.findByProduct(colourway.product_id);
    if (existing) return existing;

    const sku =
      colourway.skus.find((candidate) => candidate.size === size) ??
      colourway.skus[0];
    const item: WishlistItem = {
      item_id: `wi_user_${colourway.product_id}_${size}`,
      role: USER_SAVED_ROLE,
      parent_product_id: parent.parent_product_id,
      product_id: colourway.product_id,
      sku: sku?.sku ?? `sku_missing_${colourway.product_id}`,
      colour: colourway.colour,
      size,
      saved_at: savedAt,
      // The price and seller *at the moment of saving*, which is what makes a
      // later change detectable at all -- revalidate() compares against these
      // to raise price_changed and seller_changed.
      price_at_save: colourway.price,
      seller_at_save: colourway.seller,
    };
    this.state = [...this.state, item];
    this.version += 1;
    return item;
  }

  remove(productId: number): void {
    const next = this.state.filter((item) => item.product_id !== productId);
    if (next.length === this.state.length) return;
    this.state = next;
    this.version += 1;
  }

  toggle(
    parent: ParentProduct,
    colourway: Colourway,
    size: string,
    savedAt: string
  ): "added" | "removed" {
    if (this.isSaved(colourway.product_id)) {
      this.remove(colourway.product_id);
      return "removed";
    }
    this.add(parent, colourway, size, savedAt);
    return "added";
  }
}

/**
 * The size a heart tap records when the user has not picked one.
 *
 * A grid tile has no size control, so saving from one has to choose. It
 * prefers a size actually in stock, because saving a variant that cannot be
 * bought would put the user straight into a recovery state they did nothing
 * to cause. Failing that it takes the middle of the ladder rather than the
 * first, which on a real ladder is the extreme small end.
 *
 * The choice is disclosed rather than hidden: callers name the saved variant
 * in the confirmation, so "Saved: Blue · M" is never the first time the user
 * learns which size was recorded. For the accessories -- watches, sunglasses,
 * wallets, belts -- the ladder is a single "Onesize" and there is nothing to
 * choose, so the question does not arise at all.
 */
export function defaultSizeFor(parent: ParentProduct, inStock: string[]): string {
  const preferred = parent.sizes.find((size) => inStock.includes(size));
  if (preferred) return preferred;
  return parent.sizes[Math.floor(parent.sizes.length / 2)] ?? "Onesize";
}
